# Generated by Django 5.2.8 on 2025-11-25 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('waiter_first_approach_time', models.DateTimeField(blank=True, null=True)),
                ('bill_closed_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('cleaning_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('served', 'Served'), ('closed', 'Closed'), ('cleaned', 'Cleaned')], default='open', max_length=16)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cameras.tablezone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
